import { test } from "tap"

import * as functional from "./index"

test("@mwm/functional public exports", t => {
  const actual = Object.keys(functional).sort()
  const expected = [
    "always",
    "assoc",
    "bind",
    "blackbird",
    "both",
    "clone",
    "complement",
    "compose",
    "curry",
    "curryN",
    "defaultTo",
    "either",
    "equals",
    "F",
    "filter",
    "has",
    "head",
    "identity",
    "ifElse",
    "iife",
    "init",
    "invoker",
    "isDefined",
    "isEmpty",
    "isFunction",
    "isNil",
    "join",
    "last",
    "map",
    "merge",
    "not",
    "partial",
    "pipe",
    "pipeV",
    "prop",
    "reduce",
    "reduceRight",
    "replace",
    "slice",
    "sort",
    "split",
    "T",
    "tail",
    "take",
    "tap",
    "toUnary",
    "toVariadic",
    "trim",
    "uncurry",
    "unless",
  ].sort()
  t.isEquivalent(actual, expected)
  t.end()
})
