import { describe } from "../lib/describe.ts";
import * as functional from "./index.ts";

describe("module exports", ({ assert }) => {
  const actual = Object.keys(functional).sort();
  const expected = [
    "always",
    "assoc",
    "bind",
    "blackbird",
    "both",
    "cap",
    "clone",
    "complement",
    "compose",
    "curry",
    "curryN",
    "defaultTo",
    "either",
    "equals",
    "F",
    "filter",
    "has",
    "head",
    "identity",
    "ifElse",
    "iife",
    "init",
    "invoker",
    "isDefined",
    "isEmpty",
    "isFunction",
    "isNaN",
    "isNil",
    "isNumber",
    "isString",
    "join",
    "last",
    "log",
    "map",
    "merge",
    "not",
    "partial",
    "pipe",
    "pipeV",
    "prop",
    "reduce",
    "reduceRight",
    "replace",
    "slice",
    "sort",
    "split",
    "T",
    "tail",
    "take",
    "tap",
    "toArray",
    "toString",
    "toUnary",
    "toVariadic",
    "trim",
    "uncurry",
    "unless",
  ].sort();

  assert({ actual, expected });
});
